### ISSUE TITLE
Time tracking support

### ISSUE THREAD

**Issue by danfimov** [danfimov/ya_tracker_client#19]
- [x] Add a record of time spent
- [x] Edit a record of time spent
- [x] Delete a record of time spent
- [x] Get all records for an issue
- [x] Select records by parameters
